# Generated by Django 4.2.6 on 2024-05-28 14:05

from django.conf import settings
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('cpf', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='CPF inv√°lido', regex='^\\d{11}$')])),
                ('telefone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('data_de_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('grupos', models.ManyToManyField(related_name='usuario_grupos', to='auth.group')),
                ('permissoes', models.ManyToManyField(related_name='usuario_permissoes', to='auth.permission')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
